Repository KnpLabs/KnpPaginatorBundle, pull requests merged in 2020-10, with the labels that each got.

#666 improve issue template for support question
  .github/ISSUE_TEMPLATE/Support_Question.md
Labels: hacktoberfest-accepted

#665 Added new UIKit design
  README.md
  templates/Pagination/uikit_v3_pagination.html.twig
  templates/Pagination/uikit_v3_sortable.html.twig
Labels: hacktoberfest-accepted

#642 Added more information on overriding templates and translations
  README.md
  docs/templates.md
Labels: documentation

#668 📝 fix documentation
  docs/templates.md
  templates/Pagination/twitter_bootstrap_v4_pagination.html.twig
Labels: documentation, hacktoberfest-accepted
